starbucks.com: v2 + !
nimbix.zendesk.com: v2 + !
hostelworld.com: v2 + !
tfl.gov.uk: remove special
bitbucket.org: ~~atlassian.com~~ bitbucket.org
bikesharetoronto.com: v2 -last4 + @1
gov.uk: v2 -last4
decathlon.co.uk
ehic.org.uk: v2 + !
nievesdancestudio.com v2 -1

